# Generated by Django 3.2.6 on 2021-09-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_costomer_age_hotel_booking_customer_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel_booking',
        ),
    ]
